version: '3'
services:
  bibliography-server:
    image: font:3
    networks:
      - springcloud-overlay
#    ports:
#      - "9000:9000"
    command: tail -f /dev/null
networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay
